// Code generated by mockery v1.0.0
package mocks

import commands "github.com/windler/ws/app/commands"
import mock "github.com/stretchr/testify/mock"

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// GetCustomCommands provides a mock function with given fields:
func (_m *Config) GetCustomCommands() []commands.CustomCommand {
	ret := _m.Called()

	var r0 []commands.CustomCommand
	if rf, ok := ret.Get(0).(func() []commands.CustomCommand); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]commands.CustomCommand)
		}
	}

	return r0
}

// GetParallelProcessing provides a mock function with given fields:
func (_m *Config) GetParallelProcessing() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetTableFormat provides a mock function with given fields:
func (_m *Config) GetTableFormat() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetWsDir provides a mock function with given fields:
func (_m *Config) GetWsDir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
