// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// CustomCommand is an autogenerated mock type for the CustomCommand type
type CustomCommand struct {
	mock.Mock
}

// GetCmd provides a mock function with given fields:
func (_m *CustomCommand) GetCmd() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetDescription provides a mock function with given fields:
func (_m *CustomCommand) GetDescription() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *CustomCommand) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
