// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// UI is an autogenerated mock type for the UI type
type UI struct {
	mock.Mock
}

// PrintString provides a mock function with given fields: s, colorOrNil
func (_m *UI) PrintString(s string, colorOrNil ...string) {
	_va := make([]interface{}, len(colorOrNil))
	for _i := range colorOrNil {
		_va[_i] = colorOrNil[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// PrintTable provides a mock function with given fields: header, rows
func (_m *UI) PrintTable(header []string, rows [][]string) {
	_m.Called(header, rows)
}
